apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-frontend
  namespace: infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infra-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: infra-frontend
    spec:
      containers:
        - name: frontend
          image: infra-frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
