- name: Install kubectl and minikube
  hosts: local
  become: true
  tasks:
    - name: Install kubectl (Debian/Ubuntu)
      apt:
        name:
          - kubectl
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install minikube (Debian/Ubuntu)
      apt:
        name:
          - minikube
        update_cache: true
      when: ansible_os_family == "Debian"
